name: Test Extension
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v20.18.0'
      - run: npm ci
      - name: Prettier
        run: npm run prettier-check
      - name: Lint
        run: npm run lint
      - run: xvfb-run -a npm test
